print('Hello, world!\nWhat is your name?')
myName = input()
print('Its good to meet you ' + myName + '\nThe length of your name is: ' + str(len(myName)))
print('What is your age?')
myAge = input()
print('You will be ' + str(int(myAge) + 1) + ' in a year.')